# -*- coding: utf-8 -*-
"""ArvoreGen

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/172lpZ6V-EvKrs69KNJPLV7ggrFNc6c46
"""

familias = []
listaDeEntradas = []


entradaNumeros = input()
entradaSeparada = entradaNumeros.split()
M = int(entradaSeparada[0])
N = int(entradaSeparada[1])

for c in range(0, N):
    nome1Encontrado = False
    nome2Encontrado = False     
    entrada = input().lower()
    entradaSeparada = entrada.split() 
    nome1 = entradaSeparada[0]
    nome2 = entradaSeparada[2]

    #Vou buscar os nomes dentro das minhas famílias
    for iFamilias in range(0, len(familias)):
        if(nome1 in familias[iFamilias]):
            nome1Encontrado = True
        if(nome2 in familias[iFamilias]):
            nome2Encontrado = True
    
    
    if((nome1Encontrado == False) and (nome2Encontrado == False)):
        #Se não foram encontrados, adiciono uma nova familia
        familias.append([nome1, nome2])
        listaDeEntradas.append(entrada)
    elif((nome1Encontrado == True) and (nome2Encontrado == False)):
        #Se algum dos dois foram encontrados, adiciono na respectiva familia.
        listaDeEntradas.append(entrada)
        for iFamilias in range(False, len(familias)):
            if(nome1 in familias[iFamilias]):
                familias[iFamilias].append(nome2)
    elif((nome1Encontrado == False) and (nome2Encontrado == True)):
        listaDeEntradas.append(entrada)
        for iFamilias in range(False, len(familias)):
            if(nome2 in familias[iFamilias]):
                familias[iFamilias].append(nome1)
    else:
        #Se os dois foram encontrados, eu testo se a entrada ja aconteceu,
        #Se não, faço a junção das familias em que cada um está.
        if(entrada not in listaDeEntradas):
            iNome1 = -1
            iNome2 = -1
            listaDeEntradas.append(entrada)
            for iFamilias in range(0, len(familias)):
                #Aqui vou pegar o Index das familias que contem cada nome.
                if((nome1 in familias[iFamilias]) and (nome2 in familias[iFamilias])):
                    #Caso o usuário der uma entrada diferente, porém de usuários da mesma familia.
                    break
                elif(nome1 in familias[iFamilias]):
                    iNome1 = iFamilias
                elif(nome2 in familias[iFamilias]):
                    iNome2 = iFamilias
            
            #Aqui farei a junção das familias.
            if((iNome1 != -1) and (iNome2 != -1)):
                if(iNome1>iNome2):
                    familiaAux = familias[iNome1]
                    familias.pop(iNome1)
                    for c, nome in enumerate(familiaAux):
                        familias[iNome2].append(nome)
                elif(iNome2>iNome1):
                    familiaAux = familias[iNome2]
                    familias.pop(iNome2)
                    for c, nome in enumerate(familiaAux):
                        familias[iNome1].append(nome)      

print(len(familias))